### ISSUE TITLE
Do you have  a matlab code for Tendon Static Case

### ISSUE THREAD

**Issue by jiefengsun** [JohnDTill/ContinuumRobotExamples#1]
Great job. By the way, do you have a Matlab code for Tendon Static Case?

**Comment by JohnDTill** [comment]
Thanks! I added a Matlab script for the basic model with tendons at a constant offset and tension as the control input. It generates ".dat" output files just like the C++ version so that the model can be rendered in Blender. Let me know if any part of the code is under-commented.

**Comment by jiefengsun** [comment]
> Thanks! I added a Matlab script for the basic model with tendons at a constant offset and tension as the control input. It generates ".dat" output files just like the C++ version so that the model can be rendered in Blender. Let me know if any part of the code is under-commented.

That's great! Thanks!

**Comment by JohnDTill** [comment]
No problem. Let me know if there's anything else.
