### ISSUE TITLE
typos in the documentation CosseratRodIvpSolution.pdf

### ISSUE THREAD

**Issue by feilong926** [JohnDTill/ContinuumRobotExamples#10]
in your documentation you have:
v = Kse*R.'*n + [0;0;1];
u = Kbt*R.'*m;

whereas it shoule be:
v = Kse^-1*R.'*n + [0;0;1];
u = Kbt^-1*R.'*m;

**Comment by JohnDTill** [comment]
Yes, thank you for noticing and pointing that out. That has been patched to invert the stiffness matrices. Please let me know if you find any other issues!

**Comment by feilong926** [comment]
> Yes, thank you for noticing and pointing that out. That has been patched to invert the stiffness matrices. Please let me know if you find any other issues!

Your response was quick !
