### ISSUE TITLE
Questions regarding the formulation of the static equation in 01_Statics/02_CSG_Inverse_Kinematics/CSG_Inverse_Kinematics.pdf

### ISSUE THREAD

**Issue by rodriguesvinay** [JohnDTill/ContinuumRobotExamples#16]
the pdf on page.2 says "array 'r'  which contains the translation from the end effector to the rod attachment points in
the end effector frame" and you used 'r' in the EM summation. Isn't for the EM summation we need `p_i(L_i) x n_i`   instead of `R. r_i x n_i` in reference frame?

**Comment by JohnDTill** [comment]
Hi Rodrigues, both versions are correct. The expression `sum over i of -p_i(L_i) x n_i - m_i` is the sum of moments about the origin. The expression `sum over i of -R*r_i x n_i - m_i` is the sum of moments about the end effector. In static equilibrium, the sum of moments at any point will be zero, so we are free to pick the point which is most convenient.

**Comment by rodriguesvinay** [comment]
Hello John, thanks for the explanation. Just curious why it was convenient for you to choose the `R. r_i` expression?

**Comment by JohnDTill** [comment]
Probably it was chosen based on the intuition of summing loading on the end-effector at it's centroid, which I find a bit simpler conceptually when formulating the model. However, that does involve an unnecessary rotation which isn't present in the expression you suggest, so I don't really have a preference for one over the other!

**Comment by rodriguesvinay** [comment]
Hello john, I am sorry I forgot to mention that in formulation of EM, why didn't you considered `-pd x F` or am I missing somethin?

**Comment by JohnDTill** [comment]
Right, when considering a force on the end effector, there is an additional term in the sum of moments equation for the force. This additional term reduces to zero when summing moments at the end effector centroid, because the centroid is the point of force application, and the moment arm is zero.

**Comment by rodriguesvinay** [comment]
Hello john,  I was curious if I can contact you through email or something for general conceptual questions instead of opening an issue. I am working on my thesis topic "Kinetostatic analysis of a 6 RUS parallel continuum robot". My email address is **** and you can ping  me if it sounds good. Thanks.

**Comment by JohnDTill** [comment]
Sure thing, I sent you an email
