### ISSUE TITLE
External force on an arbitry point. 

### ISSUE THREAD

**Issue by jiefengsun** [JohnDTill/ContinuumRobotExamples#2]
Hi John,

All your simulated cases are with force at the tip.
I want o know how you deal with the force that is not at the tip.  For example, there is a force Fe = [0 1,2] at s = L/2, which is at the middle of the robot. 

I guess, if there is only one force, probably just need to change the boundary condition. If there are multiple forces at different location of the robot, it will be more complicated. 
![image](https://user-images.githubusercontent.com/31747948/57728144-6a09d000-7650-11e9-87e2-29dde7c8827b.png)

Thank you!

**Comment by JohnDTill** [comment]
Hello Jiefeng,

An extra point force at the middle of the robot results in a step change to the internal loading 'n', which can be accommodated by piecewise integration. For instance, the MATLAB rod IVP example can be changed to include a midpoint force by the following:

`%Piecewise Numerical Integration w/ step change in internal force
F_mid = [0;1;2];                       %A discrete external force, applied at the midpoint
y0 = [p0; reshape(R0,9,1); n0; m0];    %Combine states into single state vector
[~,y1] = ode45(@RodODE,[0 L/2],y0);    %Numerically integrate from the base to the midpoint
y_mid = y1(end,:).';                   %Create a variable for the midpoint state vector
y_mid(13:15) = y_mid(13:15) - F_mid;   %Apply the change in step loading
[~,y2] = ode45(@RodODE,[L/2 L],y_mid); %Continue integrating to the end
y = [y1; y2];                          %Join the two state matrices for plotting or other uses`

It would be complicated with many point forces. You could do iterative piecewise integrations in a loop, or you could come up with some scheme to approximate the point forces as part of the distributed force term.

**Comment by jiefengsun** [comment]
Hello John,

Thank you so much for your quick response!
I tried to approximate the point forces as part of the distributed force term. For the static BVP one, I used a free end as a boundary condition in the shooting method. And add a term to the distributed force 'n'.  But I am not sure it's correct or not. 
![image](https://user-images.githubusercontent.com/31747948/57871739-461cca80-77c7-11e9-8eb1-2157294ac36e.png)

**Comment by JohnDTill** [comment]
The scenario is that you have two discrete forces at s = 10 and s = 40? In that case, the above is mostly correct, except that Fe should be negated, i.e. ns = -rho*A*g - Fe/(10.5-9.5), since ns = -f. Also, the "s == 9 < s" term is an easy to make typo which has given me grief in the past!

You could even add a parameter to control the width of the approximate distributed force, say 'a', so that you would have
`
if s > 10-a && s < 10+a
   ns = -rho*A*g - Fe/(2*a);
elseif ...
`

And of course, you'll need to make sure the numerical integration step size is sufficiently smaller than the width of the approximate distributed force so that you sample several points in the region.

**Comment by jiefengsun** [comment]
Hi John, 
Thank you so much for your help!
I attended the ICRA conferenced last week and one guy from your group helped me to understand more about how to apply several forces at different locations. 
Thank you again and have a nice day!

--Jiefeng

**Comment by JohnDTill** [comment]
Glad to hear it! You're welcome, and have a good day as well!

**Comment by xlsufo** [comment]
> Hi John, Thank you so much for your help! I attended the ICRA conferenced last week and one guy from your group helped me to understand more about how to apply several forces at different locations. Thank you again and have a nice day!
> 
> --Jiefeng

Hi Jiefeng,
Can you give me some advice on how to apply several forces at different locations?

**Comment by jiefengsun** [comment]
> 

Hello xlsufo, 
Please take a look at John's response to me. 
You can either use a piece-wised integration or use a distributed load to simulate a force at an arbitrary point. 
Shortly, I will publish a paper that will include a very good example of this case and the code will be open source as well.
If you have any questions please directly send me an email or comment on my GitHub repositories so that I will be able to receive direct notifications. 


Best, 
Jiefeng
