### ISSUE TITLE
When tension of tendon is larger, such as tau=20, the solver stopped prematurely.

### ISSUE THREAD

**Issue by zhangxue122** [JohnDTill/ContinuumRobotExamples#6]
Hello John,

Thank you for your work and I learned so much from your work. 

I have run the 05_Tendon_Robot.m. I found when the tension of tendon /tau is larger, the solver stopped prematurely. If it because I didn't pick the init_guess right?

Thanks again,
Xue

**Comment by JohnDTill** [comment]
Hello Xue,

The convex optimization problem does have worse conditioning with a larger tau, making it more difficult to solve. You could try changing the fsolve settings to allow more iterations and have a tighter cutoff tolerance. Parameter stepping the tension is also a good option; when tau = [45, 0, 0, 0] is too hard on the solver, you could often have better luck solving tau = [15, 0, 0, 0], then using that solution as the initial guess for tau = [30, 0, 0, 0], then tau = [45, 0, 0, 0].

What tension is it failing to solve at? Unfortunately I do not have a MATLAB license to run 05_Tendon_Robot.m, but for the C++ version the solver fails somewhere between tau = [150, 0, 0, 0]N and tau = [200, 0, 0, 0]N. The scenario is already not very realistic at tau = [150, 0, 0, 0]N; the robot doubles back on itself.
![TendonRobot](https://user-images.githubusercontent.com/22652588/84679551-6acdff00-aeff-11ea-9e76-24c8e418a3c3.jpg)
Hopefully the MATLAB script has similar behavior!

**Comment by jiefengsun** [comment]
Hello John,

Iterative solving the problem that has a large tau is a good idea. However, it does not work for a dynamic problem, for example, a large force is suddenly applied to the tender driven manipulator. It is very difficult to find a correct initial guess, especially, the time step is large. But to avoid "catastrophic cancellation" we cannot make the time step pretty small. What do you think of this problem? Do you think this is a drawback compared with the conventional way of solving PDEs, first spatial discretization then time discretization? I haven't tried but I feel the conventional way will be able to handle the case that a large force is suddenly applied, or the force has a large sudden change. 

Best,
Jiefeng

**Comment by JohnDTill** [comment]
Yes, using an implicit method for time integration is great for large time steps, but may cause problems at small time steps. Part of the issue is that shooting methods can have problems with poor conditioning. In an upcoming paper, we couldn't simulate concentric tube snapping with the shooting method, but we could use a finite difference scheme with the implicit time approach. The conventional way can work, but the time step needs to be small enough to meet the CFL condition, which can be quite limiting.

**Comment by jiefengsun** [comment]
Thanks! Does 'poor conditioning' mean it is quite difficult to get the correct initial guess? The problem that I currently work on has a complicated shape (that has several possible static configurations that are close), a very small time step has to be chosen to make sure the initial guess is close enough.  So I have to switch to the conventional method, but as you said CFL condition is limiting. I hope your new method can be helpful and look forward to reading your upcoming paper!

Best,
Jiefeng

**Comment by JohnDTill** [comment]
Right, elements of the gradient descent Jacobian go to infinity if the guess is too far off, but with a close enough guess you can have a manageable slope.
